# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: ghcjs-0.2.0.20151001_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151001_ghc-7.10.2:
        url: "https://github.com/fizruk/ghcjs/releases/download/v0.2.0.20151001/ghcjs-0.2.0.20151001.tar.gz"

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: git@github.com:rimmington/ghcjs-servant-client
    commit: dd9cdf67223b2c8dae17a53faa17f33424644cd7
  extra-dep: true
- location:
    git: git@github.com:rimmington/eclogues
    commit: d6b00f84294d2a6ef351caec215f23998763ba46
  extra-dep: true
  subdirs:
  - eclogues
- location:
    git: git@github.com:rimmington/uuid-aeson
    commit: 634f244564444ea4b700bcfca1211c261bcecf9f
  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- either-4.4.1
- exceptions-0.8.0.2
- http-media-0.6.2
- http-types-0.9
- lens-4.13
- microlens-0.3.4.1
- network-uri-2.6.0.3
- path-0.5.2
- react-flux-1.0.1
- safe-0.3.9
- servant-0.4.4.5
- split-0.2.2
- string-conversions-0.4
- uuid-types-1.0.2
- MonadRandom-0.4
- base-orphans-0.4.4
- bifunctors-5
- blaze-builder-0.4.0.1
- bytestring-conversion-0.3.1
- comonad-4.2.7.2
- contravariant-1.3.3
- distributive-0.4.4
- free-4.12.1
- kan-extensions-4.2.3
- mmorph-1.0.4
- monad-control-1.0.0.4
- parsec-3.1.9
- profunctors-5.1.1
- random-1.1
- reflection-2.1
- semigroupoids-5.0.0.4
- semigroups-0.17.0.1
- tagged-0.8.1
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- utf8-string-1.0.1.1
- void-0.7.1
- StateVar-1.1.0.1
- adjunctions-4.2.2
- double-conversion-2.0.1.0
- nats-1
- prelude-extras-0.4.0.2

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
